name: Maven CI with JUnit5, Allure & JaCoCo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Build & Run Tests (JUnit5 + Allure + JaCoCo)
      - name: Build, Test & Coverage
        run: mvn clean test jacoco:report

      # 4. Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      # 5. Upload Allure Raw Results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          if-no-files-found: ignore

      # 6. Upload Allure HTML Report
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          if-no-files-found: ignore

      # 7. Upload JaCoCo Coverage Report
      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
          if-no-files-found: ignore
